### ISSUE TITLE
Skyview

### ISSUE THREAD

**Issue by stgruber** [geocryology/HorizonPy#10]
Make a function that computes the sky-view factor based on a horizon line and slope & aspect. This will use the hemisphere tessellation.... The contribution of each discrete patch of the hemisphere to the overall sky-view factor varies with the cosign between its vector and the surface normal. This is why it depends on slope and aspect.

Somewhere in this PhD should be the basic theory:
http://opac.nebis.ch:80/F/S8KI84IA364J2KT5NL3JFANNK1UJL4D6B71Q7Y3PGS87QFKNHL-03357?func=service&doc_library=EBI01&doc_number=005806109&line_number=0001&func_code=WEB-FULL&service_type=MEDIA%22

**Comment by nicholas512** [comment]
One needs a NEBIS account to access the document in the link.  Is there a fixed pdf link available somewhere?

**Comment by nicholas512** [comment]
I don't think the hemisphere tesselation is needed.  The thesis gives the equation for the sky-view factor as (p.62) :

<a href="https://www.codecogs.com/eqnedit.php?latex=\frac{1}{2\pi}&space;\int_{0}^{2\pi}&space;cos^2(\theta_h(\phi))&space;d\phi" target="_blank"><img src="https://latex.codecogs.com/gif.latex?\frac{1}{2\pi}&space;\int_{0}^{2\pi}&space;cos^2(\theta_h(\phi))&space;d\phi" title="\frac{1}{2\pi} \int_{0}^{2\pi} cos^2(\theta_h(\phi)) d\phi" /></a>

Probably the equation where you integrate over solid sky angles (hemisphere tesselation) multiplied by the angle between them would be useful when the sky isn't open (e.g. for forest canopies where there are lots of little patches):

<a href="https://www.codecogs.com/eqnedit.php?latex=F_{sky}&space;=&space;\frac{1}{2\pi}&space;\int_{sky}&space;cos(\theta)&space;d\Omega" target="_blank"><img src="https://latex.codecogs.com/gif.latex?F_{sky}&space;=&space;\frac{1}{2\pi}&space;\int_{sky}&space;cos(\theta)&space;d\Omega" title="F_{sky} = \frac{1}{2\pi} \int_{sky} cos(\theta) d\Omega" /></a>

I expect t hat the math simplifies somewhat because for a given azimuthal angle, you just integrate from the horizon line to 90 degrees.

This has been coded in the SkyView.py file
