### ISSUE TITLE
Digitization conventions

### ISSUE THREAD

**Issue by stgruber** [geocryology/HorizonPy#8]
- have 72 spokes in wheel, or allow setting n_spokes
- if no point exists between spokes, this is interpreted as 90º horizon (otherwise difficult to digitize)
- if a click occurs at an elevation below 0º, this is interpreted as 0 (unobstructed)

**Comment by nicholas512** [comment]
have 72 spokes in wheel, or allow setting n_spokes
*  Can now specify spokes in Azimuth > draw azimuth grid > custom_grid

if no point exists between spokes, this is interpreted as 90º horizon (otherwise difficult to digitize)
* To get 90º horizon, you can right-click outside the boundary of the grid. 

if a click occurs at an elevation below 0º, this is interpreted as 0 (unobstructed)
* implemented
